# Generated by Django 4.2.3 on 2023-07-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_id',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
