# Generated by Django 4.2.3 on 2023-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_userprofile_fname_userprofile_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
