# Generated by Django 4.2.3 on 2023-08-01 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment', unique=True),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='reaction',
            field=models.BooleanField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('user', 'comment')},
        ),
    ]
