# Generated by Django 4.2.3 on 2023-08-01 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_commentreaction_comment_commentreaction_reaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
