# Generated by Django 4.2.3 on 2023-08-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_commentreaction_user_alter_commentreaction_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
