# Generated by Django 4.2.3 on 2023-09-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_blogpost_author_name_blogpost_blog_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogger',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog_post',
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReaction',
        ),
    ]
