# Generated by Django 4.2.3 on 2023-09-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_remove_blogpost_blogger_remove_comment_blog_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
